language: c
sudo: false
notifications: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - mkdir -p $HOME/arduino_ide/libraries/
  - cd $HOME/arduino_ide/libraries/
  - git clone -o cf7b4a6 https://github.com/Makuna/NeoPixelBus
  - git clone -o b05d455 https://github.com/PaulStoffregen/Time
  - git clone -o 3c22f2f https://github.com/gmag11/NtpClient
  - git clone -o b592ac6 https://github.com/me-no-dev/ESPAsyncUDP
  - git clone -o ec56354 https://github.com/interactive-matter/aJson
  - git clone -o cadf6b4 https://github.com/tablatronix/WiFiManager
  - sed -i -e 's|#define PRINT_BUFFER_LEN 256|#define PRINT_BUFFER_LEN 4096|g'  aJson/aJSON.h
  - cd aJson
  - curl -OSLs https://gitlab.com/xarduino/lightsw/raw/2424e3a9348e7144373311af132ced38f14489ba/patch/ajson-void-flush.patch
  - git apply ajson-void-flush.patch
  - rm ajson-void-flush.patch
  - cd $TRAVIS_BUILD_DIR
script:
  - build_platform esp8266
